### ISSUE TITLE
Fix Youtube API Error when API key is invalid

### ISSUE THREAD

**Issue by sdthaker** [Curio-org/Curio#52]
When the Youtube API key is set to an invalid key, the application shows an ambiguous error message to the client: 

<img width="2056" alt="image" src="https://github.com/Curio-org/Curio/assets/71615163/63e5ecf0-515c-4055-b19b-a34c1d99c8e0">

Ideally, the above error message shouldn't be shown to the client. Also, the application should show an error message in the console saying the API key is invalid and any other useful message we get from the API response.

**Comment by arjxn-py** [comment]
Thanks @sdthaker for opening this.
In case you want to pick this up, feel free.

**Comment by sdthaker** [comment]
Sure please assign it to me, I'll get it in soon. Already have the code written for it.
