### ISSUE TITLE
Feature: add home page link when logo is clicked

### ISSUE THREAD

**Issue by sdthaker** [Curio-org/Curio#53]
Currently, when the user clicks on the Curio logo, nothing happens. Add a link on the logo div to navigate the user to the home page when they click on it.

**Comment by mnajibi** [comment]
Hi,

I'd like to work on the issue. Could you please assign this to me?

Thanks,
Maryam

**Comment by arjxn-py** [comment]
Hi @mnajibi, feel free to open a PR and discuss the resolution of issues while setting up.
Thanks.

**Comment by sdthaker** [comment]
I and @mnajibi are classmates, taking an open-source course together where we have to put out 4 PRs as part of the assignment during the month of October. So I created this issue for her and asked her to comment on this so she a take it. LOL! :) @arjxn-py

**Comment by arjxn-py** [comment]
Haha that's really nice. I hope you both are having nice experience with open-source, best of luck with your open-source journey in and beyond October. Happy to help whenever 🙂.
