### ISSUE TITLE
Redesign `Send us the Video` form in footer

### ISSUE THREAD

**Issue by arjxn-py** [Curio-org/Curio#61]
Currently the form looks like this - 
![image](https://github.com/Curio-org/Curio/assets/104268427/7caabfb0-a233-4b62-a35f-41193a463ed8)
We want it to be decent looking and not out of the place like right now.

**Comment by AmosBlack** [comment]
id like to do it

**Comment by arjxn-py** [comment]
Sure @AmosBlack, feel free to open a PR for the same. Thanks

**Comment by arjxn-py** [comment]
You can consider removing this - 
![image](https://github.com/Curio-org/Curio/assets/104268427/b44c907f-f164-4ac7-8a9a-18682f078ff3)

**Comment by AmosBlack** [comment]
Hey arjxn-py, just created a PR for this, do check it out. Thanks
