### ISSUE TITLE
Docs: Improve Underheader's content

### ISSUE THREAD

**Issue by arjxn-py** [Curio-org/Curio#62]
## Description

The main page content of CURIO plays a crucial role in conveying our platform's value to users. It's the first impression that visitors have of CURIO, and it should effectively communicate its purpose and benefits. However, there is a lot of room for improvement in the current content.

## Objective:

The objective of this issue is to enhance the main page content of CURIO to make it more engaging, informative, and relevant to the users. This improvement aims to provide a better user experience and to clearly convey what CURIO is and how it can benefit different user groups.

**Comment by arjxn-py** [comment]
For context, current content on Underheader looks like this - 
![image](https://github.com/Curio-org/Curio/assets/104268427/b931ce86-b096-45cb-b636-95cc4398f7ff)

**Comment by Saswatsusmoy** [comment]
I guess we can start by defining our goals and by explaining the tool

I've worked upon this idea and I think we can implement the following:


What is Curio: Welcome to Curio, a remarkable web application designed to address the language and communication barriers between mentors and learners. Our platform serves as an open space where individuals can translate their favorite YouTube videos into their desired languages, fostering a sense of connection and understanding.

Translator: At its current stage of development, Curio offers translation and viewing functionalities, with plans to expand into machine dubbing in the future

Replace 'Knowledgebase' and 'Education' with 'Innovation' and 'Validation' respectively.

Innovation: One of the most intriguing aspects of Curio is its ability to link students studying different languages. We provide a platform where these language enthusiasts can come together and put their skills to the test through audio dubbing. By dubbing videos in the languages they are learning, students can immerse themselves in real-world language practice and gain valuable experience.

Validation: Curio takes this innovative approach a step further by incorporating a validation process. After students submit their dubbed audio, it undergoes a thorough review. We compare the transcript of the dubbed audio with the converted transcript of the original audio in the dubbed language, using the reliable Google Translator. This meticulous validation process ensures that the dub meets the minimum criteria for acceptance, guaranteeing the quality and accuracy of the dubbed content.

Replace "The possibilities are beyond your imagination" with "Explore the intricate web of possibilities, where every choice has a precise ripple effect"

Replace "Explore the tool" with "Start Translating Now"

**Comment by arjxn-py** [comment]
Thanks @Saswatsusmoy, proposed content looks awesome 💯
Will review your PR in some time.

**Comment by Saswatsusmoy** [comment]
> Thanks @Saswatsusmoy, proposed content looks awesome 💯 Will review your PR in some time.

Thanks for the feedback, would like to put in more input wherever possible

**Comment by arjxn-py** [comment]
> Thanks for the feedback, would like to put in more input wherever possible

That's really nice, feel free to pick up or open issues whichever you feel can help improve the project.
Happy to work with you 🚀
