### ISSUE TITLE
Create Issue and PR Templates

### ISSUE THREAD

**Issue by Saswatsusmoy** [Curio-org/Curio#79]
Create templates for raising an issue or PR to maintain uniformity and for better documentation purposes

**Comment by bhavik001** [comment]
Hey @arjxn-py 
Can you please assign me to work on this issue and can you please label this as a hactoberfest.

Please reply!
Thank you!

**Comment by arjxn-py** [comment]
Although hacktoberfest is over I've labelled it and assigned it to you 🙂

**Comment by bhavik001** [comment]
Hey, Can you please merge the pull request if everything is good?

**Comment by arjxn-py** [comment]
Hi, I've reviewed the changes on your branch. Do let me know in case of any doubt.

**Comment by bhavik001** [comment]
Hey @arjxn-py I have created 2 separate files. Can you please review it!
